# Generated by Django 2.1.3 on 2018-11-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('reviewDate', models.DateField()),
                ('termTaken', models.DateField()),
                ('className', models.TextField()),
                ('courseNum', models.TextField()),
                ('couseSubject', models.TextField()),
                ('school', models.TextField()),
                ('review', models.TextField()),
                ('teacherName', models.TextField()),
            ],
        ),
    ]
