# Generated by Django 2.1.3 on 2018-11-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewerName',
            field=models.TextField(default='anon'),
        ),
        migrations.AlterField(
            model_name='review',
            name='termTaken',
            field=models.TextField(),
        ),
    ]
