# Generated by Django 2.1.3 on 2018-11-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20181117_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='couseSubject',
            new_name='courseSubject',
        ),
    ]
